---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-agent
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/component: gpu-agent
spec:
  selector:
    matchLabels:
      name: gpu-agent
      app.kubernetes.io/component: gpu-agent
  template:
    metadata:
      labels:
        name: gpu-agent
        app.kubernetes.io/component: gpu-agent
    spec:
      nodeSelector:
        n8s.nebuly.ai/gpu-partitioning: "gpu-agent"
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      # Mark this pod as a critical add-on; when enabled, the critical add-on
      # scheduler reserves resources for critical add-on pods so that they can
      # be rescheduled after a failure.
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      priorityClassName: "system-node-critical"
      containers:
        - name: gpu-agent
          image: gpu-agent:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/pod-resources/kubelet.sock
            - name: run-nvidia
              mountPath: /run/nvidia
              mountPropagation: HostToContainer
      terminationGracePeriodSeconds: 30
      serviceAccountName: gpu-agent
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/pod-resources/kubelet.sock
        - name: run-nvidia
          hostPath:
            path: /run/nvidia
            type: Directory
