---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nos-nebuly-ai-v1alpha1-compositeelasticquota
  failurePolicy: Fail
  name: vcompositeelasticquota.kb.io
  rules:
  - apiGroups:
    - nos.nebuly.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - compositeelasticquotas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nos-nebuly-ai-v1alpha1-elasticquota
  failurePolicy: Fail
  name: velasticquota.kb.io
  rules:
  - apiGroups:
    - nos.nebuly.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - elasticquotas
  sideEffects: None
