apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "operator.name" . }}
spec:
  dnsNames:
    - {{ include "operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "n8s.selfSignedCertIssuerName" . }}
  secretName: {{ include "operator.webhookCertSecretName" . }}
