---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: nebuly/rabbitmq-producer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_HOST
              value: "my-cluster"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_QUEUE
              value: "messages"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: nebuly/rabbitmq-consumer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_HOST
              value: "my-cluster"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_QUEUE
              value: "messages"
