---
apiVersion: v1
kind: Secret
metadata:
  name: guest-user-credentials
type: Opaque
stringData:
  username: guest
  password: guest
  uri: https://my-cluster:15672 # uri for the management api; when scheme is not provided in uri, operator defaults to 'http'

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: guest-user
spec:
  rabbitmqClusterReference:
    name: my-cluster
  importCredentialsSecret:
    name: guest-user-credentials

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: guest-user-permissions
spec:
  vhost: "/"
  userReference:
    name: "guest-user"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: my-cluster