header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: nebuly.com
    software-name: nos

  paths-ignore:
    - 'config/**'
    - '.*'
    - '.*/**'
    - 'Makefile'
    - 'bin/**'
    - 'hack/**'
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - '**/go.mod'
    - '**/go.sum'
    - 'LICENSE'
    - 'NOTICE'
    - 'helm-charts/'
    - 'doc/**'
    - 'docs/**'
    - 'demos/**'

  language:
    Go:
      extensions:
        - ".go"
      comment_style_id: SlashAsterisk

dependency:
  files:
    - go.mod
