apiVersion: config.nos.nebuly.ai/v1alpha1
kind: OperatorConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: operator.nos.nebuly.ai
# leaderElectionReleaseOnCancel defines if the leader should step down volume
# when the Manager ends. This requires the binary to immediately end when the
# Manager is stopped, otherwise, this setting is unsafe. Setting this significantly
# speeds up voluntary leader transitions as the new leader don't have to wait
# LeaseDuration time first.
# In the default scaffold provided, the program ends immediately after
# the manager stops, so would be fine to enable this option. However,
# if you are doing or is intended to do any operation such as perform cleanups
# after the manager stops then its usage might be unsafe.
  leaderElectionReleaseOnCancel: true

# Defines how many GB of memory each nvidia.com/gpu resource has.
# Should be equal to scheduler arg "nvidiaGpuResourceMemoryGB" (scheduler_config.yaml)
nvidiaGpuResourceMemoryGB: 32
