apiVersion: v2
name: nos-gpu-partitioner
description: Automatically partitions GPUs exposing them to Kubernetes as multiple resources (slices).

type: application
version: 0.0.1-alpha.3
appVersion: "0.0.1-alpha.3"

sources:
  - https://github.com/nebuly-ai/nos
  - https://github.com/nebuly-ai/nos-gpu-partitioner

maintainers:
  - name: Michele Zanotti
    email: m.zanotti@nebuly.ai
    url: github.com/Telemaco019
  - name: Diego Fiori
    email: d.fiori@nebuly.ai
    url: github.com/diegofiori
