apiVersion: n8s.nebuly.ai/v1alpha1
kind: CompositeElasticQuota
metadata:
  name: composite-quota-a
  namespace: namespace-a
spec:
  namespaces:
    - team-a
    - team-b
    - team-c
  min:
    cpu: 10m
