apiVersion: n8s.nebuly.ai/v1alpha1
kind: CompositeElasticQuota
metadata:
  name: composite-quota-a
  namespace: namespace-x # Could as well be any of the namespaces specified by field "namespaces"
spec:
  namespaces:
    - team-a
    - team-b
    - team-c
  min:
    cpu: 10
    n8s.nebuly.ai/gpu-memory: 24
