apiVersion: nos.nebuly.com/v1alpha1
kind: CompositeElasticQuota
metadata:
  name: composite-quota-a
  namespace: namespace-x # Could as well be any of the namespaces specified by field "namespaces"
spec:
  namespaces:
    - team-a
    - team-b
    - team-c
  min:
    cpu: 10
    nos.nebuly.com/gpu-memory: 24
