apiVersion: nos.nebuly.ai/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-a
  namespace: team-a
spec:
  min:
    cpu: 2
  max:
    cpu: 10

---

apiVersion: nos.nebuly.ai/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-b
  namespace: team-b
spec:
  min:
    cpu: 2
    nos.nebuly.ai/gpu-memory: 16
