resources:
- deployment.yaml
- namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - scheduler_config.yaml
  name: scheduler-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: scheduler
  newName: ghcr.io/telemaco019/nebulnetes-scheduler
  newTag: 0.0.1-alpha.2
