apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  resourceNamespace: kube-system
  resourceName: n8s-scheduler
profiles:
- schedulerName: n8s-scheduler
  plugins:
    preFilter:
      enabled:
        - name: CapacityScheduling
    postFilter:
      enabled:
        - name: CapacityScheduling
      disabled:
        - name: "*"
    reserve:
      enabled:
        - name: CapacityScheduling
  pluginConfig:
    - name: CapacityScheduling
      args:
        # Defines how many GB of memory each nvidia.com/gpu resource has.
        # Should be equal to controller-manager config field "nvidiaGpuResourceMemoryGB" (controller_manager_config.yaml)
        nvidiaGpuResourceMemoryGB: 32
