apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mig-agent.config.configMapName" . }}
data:
  {{ include "mig-agent.configFileName" . }}: |-
    apiVersion: config.n8s.nebuly.ai/v1alpha1
    kind: MigAgentConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: false
    reportConfigIntervalSeconds: {{ .Values.migAgent.reportConfigIntervalSeconds}}
