apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scheduler.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "scheduler.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scheduler.name" . }}
    namespace: n8s-system
