apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: scheduler
  name: scheduler
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
    spec:
      serviceAccountName: scheduler
      containers:
      - args: [
        "--config",
        "/etc/kubernetes/scheduler_config.yaml",
        "--leader-elect",
        "--v",
        "1" # debug
        ]
        image: scheduler:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes
          readOnly: true
      hostNetwork: false
      hostPID: false
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config

