site_name: nos

docs_dir: ./docs

nav:
  - Installation: installation.md
  - Overview: overview.md
  - Dynamic GPU Partitioning: dynamic-gpu-partitioning.md
  - Elastic Resource Quota: elastic-quota.md
  - Developer:
      - Getting started: developer/getting-started.md
      - Contribution guidelines: developer/contribution-guidelines.md
  - Helm Charts:
      - nos: helm-charts/nos/README.md
      - GPU Partitioner: helm-charts/nos-gpu-partitioner/README.md
      - Operator: helm-charts/nos-operator/README.md
      - Scheduler: helm-charts/nos-scheduler/README.md
