---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nos.nebuly.com
  resources:
  - compositeelasticquotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nos.nebuly.com
  resources:
  - compositeelasticquotas/finalizers
  verbs:
  - update
- apiGroups:
  - nos.nebuly.com
  resources:
  - compositeelasticquotas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nos.nebuly.com
  resources:
  - elasticquotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nos.nebuly.com
  resources:
  - elasticquotas/finalizers
  verbs:
  - update
- apiGroups:
  - nos.nebuly.com
  resources:
  - elasticquotas/status
  verbs:
  - get
  - patch
  - update
