# Default values for nebulnetes-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# -- The prefix used for generating all the resource names.
namePrefix: n8s

# -- The level of log of the controller manager.
# Zero corresponds to `info`, while values greater or equal than 1 corresponds to higher debug levels.
# **Must be >= 0**.
logLevel: 0

# -- Number of replicas of the controller manager Pod.
replicaCount: 1

# -- Defines how much GB of memory does a nvidia.com/gpu has.
nvidiaGpuResourceMemoryGB: 32

image:
  # -- Sets the operator Docker repository
  repository: ghcr.io/telemaco019/nebulnetes-operator
  # -- Overrides the operator Docker image tag whose default is the chart appVersion.
  tag: ""
  # -- Sets the operator Docker image pull policy.
  pullPolicy: IfNotPresent

# -- Configuration of the [Kube RBAC Proxy](https://github.com/brancz/kube-rbac-proxy), which runs as sidecar of
# the operator Pods.
# @default -- -
kubeRbacProxy:
  logLevel: 1
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: "v0.13.0"
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi


leaderElection:
  # -- Enables/Disables the leader election of the operator controller manager.
  enabled: true

# -- Sets the security context of the operator Pod.
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

# -- Sets the resource limits and requests of the operator controller manager container.
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# -- Sets the annotations of the operator Pod.
podAnnotations: {}

# -- Sets the tolerations of the operator Pod.
tolerations: []

# -- Sets the affinity config of the operator Pod.
affinity: {}

# -- Sets the nodeSelector config of the operator Pod.
nodeSelector: {}
