# Default values for nos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# @default -- -
global:
  # -- Defines how many GB of memory each nvidia.com/gpu resource has.
  nvidiaGpuResourceMemoryGB: 32

# -- All values available [here](../nos-operator/README.md).
# @default -- -
nos-operator:
  # -- Enable or disable the `nos operator`
  enabled: true

# -- All values available [here](../nos-scheduler/README.md).
# @default -- -
nos-scheduler:
  # -- Enable or disable the `nos scheduler`
  enabled: true


# -- All values available [here](../nos-gpu-partitioner/README.md).
# @default -- -
nos-gpu-partitioner:
  # -- Enable or disable the `nos gpu partitioner`
  enabled: true

# -- If true allows to deploy `nos` chart in the `default` namespace
allowDefaultNamespace: false

# -- If true, shares with Nebuly telemetry data collected only during the Chart installation
shareTelemetry: true