apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.23.3
    kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
  - role: worker
    image: kindest/node:v1.23.3