---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mig-agent
  namespace: system
spec:
  selector:
    matchLabels:
      name: mig-agent
  template:
    metadata:
      labels:
        name: mig-agent
    spec:
      nodeSelector:
        n8s.nebuly.ai/auto-mig-enabled: "true"
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      # Mark this pod as a critical add-on; when enabled, the critical add-on
      # scheduler reserves resources for critical add-on pods so that they can
      # be rescheduled after a failure.
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      priorityClassName: "system-node-critical"
      imagePullSecrets:
        - name: ghcr # todo: remove me
      containers:
        - name: mig-agent
          image: mig-agent:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - "--config=mig_agent_config.yaml"
          securityContext:
            privileged: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/pod-resources/kubelet.sock
            - name: run-nvidia
              mountPath: /run/nvidia
              mountPropagation: HostToContainer
      terminationGracePeriodSeconds: 30
      serviceAccountName: mig-agent
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/pod-resources/kubelet.sock
        - name: run-nvidia
          hostPath:
            path: /run/nvidia
            type: Directory
