apiVersion: n8s.nebuly.ai/v1alpha1
kind: ElasticQuota
metadata:
  name: elasticquota-sample
spec:
  max:
    cpu: 6
  min:
    cpu: 4

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
      resources:
        limits:
          cpu: 100m
          memory: 128Mi