apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: team-b
spec:
  schedulerName: n8s-scheduler
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 5m
