# permissions for end users to view modeldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modeldeployment-viewer-role
rules:
- apiGroups:
  - n8s.nebuly.ai
  resources:
  - modeldeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - n8s.nebuly.ai
  resources:
  - modeldeployments/status
  verbs:
  - get
