# permissions for end users to edit modeldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modeldeployment-editor-role
rules:
- apiGroups:
  - n8s.nebuly.ai
  resources:
  - modeldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - n8s.nebuly.ai
  resources:
  - modeldeployments/status
  verbs:
  - get
