---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mig-agent-role
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list", "watch", "get", "delete" ]

