apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-partitioner
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/component: gpu-partitioner
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
    app.kubernetes.io/component: gpu-partitioner
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: gpu-partitioner
      labels:
        control-plane: controller-manager
        app.kubernetes.io/component: gpu-partitioner
    spec:
      imagePullSecrets: # todo: remove me
        - name: ghcr
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /gpupartitioner
          image: gpu-partitioner:latest
          name: gpu-partitioner
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: gpu-partitioner
      terminationGracePeriodSeconds: 10
