{{- if not (lookup "v1" "Role" (include "metricsReaderRoleName" .) .Release.Namespace) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "metricsReaderRoleName" . }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{ end }}