{{- if not (lookup "v1" "Role" (include "gpu-partitioner.authProxyRoleName" .) .Release.Namespace) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gpu-partitioner.authProxyRoleName" . }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
{{ end }}
