apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpu-partitioner.knownMigGeometriesConfigMapName" . }}
  labels:
    {{- include "gpu-partitioner.labels" . | nindent 4 }}
data:
  {{ include "gpu-partitioner.knownMigGeometriesFileName" . }}: |
    {{- .Values.knownMigGeometries | toYaml | nindent 4 }}
