# Default values for scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# -- The level of log of the scheduler.
# Zero corresponds to `info`, while values greater or equal than 1 corresponds to higher debug levels.
# **Must be >= 0**.
logLevel: 0

# -- Overrides the Kube Scheduler configuration
config: {}

# -- Number of replicas of the scheduler.
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  # -- Sets Docker image.
  repository: ghcr.io/telemaco019/nebulnetes-scheduler
  # -- Sets Docker image pull policy.
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

leaderElection:
  # -- Enables/Disables the leader election when deployed with multiple replicas.
  enabled: true

# -- Sets the resource limits and requests of the scheduler container.
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# -- Sets the annotations of the scheduler Pod.
podAnnotations: {}

# -- Sets the tolerations of the scheduler deployment.
tolerations: []

# -- Sets the affinity config of the scheduler deployment.
affinity: {}

# -- Sets the nodeSelector config of the scheduler deployment.
nodeSelector: {}

# -- Sets the security context of the scheduler container
securityContext:
  privileged: false

# -- Sets the security context of the scheduler Pod
podSecurityContext: {}

# @default -- -
global:
  # -- Defines how many GB of memory each nvidia.com/gpu resource has.
  nvidiaGpuResourceMemoryGB: 32
