apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: time-slicing-agent
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: time-slicing-agent
          args:
            - "--config=time_slicing_agent_config.yaml"
#           - "--zap-log-level=1"  # Uncomment this line to enable debug logging
          volumeMounts:
            - name: time-slicing-agent-config
              mountPath: /time_slicing_agent_config.yaml
              subPath: time_slicing_agent_config.yaml
      volumes:
        - name: time-slicing-agent-config
          configMap:
            name: time-slicing-agent-config
