apiVersion: n8s.nebuly.ai/v1alpha1
kind: ModelDeployment
metadata:
  name: sample
spec:
  modelLibrary:
    uri: https://foo.bar
    kind: azure
    secretName: azure-credentials
  sourceModel:
    uri: https://foo.bar.libar
  optimization:
    target: Latency
    modelOptimizerImageName: hello-world
    modelOptimizerImageVersion: latest
