apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mighandler-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mighandler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduler-role
subjects:
  - kind: ServiceAccount
    name: scheduler
    namespace: system
