---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gpu-partitioner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpu-partitioner-role
subjects:
  - kind: ServiceAccount
    name: gpu-partitioner
    namespace: system
