apiVersion: v2
name: gpu-partitioner
description: Automatically partitions GPUs exposing them to Kubernetes as multiple resources (slices).

type: application
version: 0.0.1-alpha.2
appVersion: "0.0.1-alpha.2"

maintainers:
  - name: Michele Zanotti
    email: m.zanotti@nebuly.ai
  - name: Diego Fiori
    email: d.fiori@nebuly.ai
