apiVersion: v2
name: nebulnetes-scheduler
description: Nebulnetes custom scheduler.

type: application
version: 0.0.1-alpha.2
appVersion: "0.0.1-alpha.2"

maintainers:
  - name: Michele Zanotti
    email: m.zanotti@nebuly.ai
    url: github.com/Telemaco019
  - name: Diego Fiori
    email: d.fiori@nebuly.ai
    url: github.com/diegofiori
