apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nos.nebuly.ai
    resources:
      - compositeelasticquotas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nos.nebuly.ai
    resources:
      - compositeelasticquotas/finalizers
    verbs:
      - update
  - apiGroups:
      - nos.nebuly.ai
    resources:
      - compositeelasticquotas/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - nos.nebuly.ai
    resources:
      - elasticquotas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nos.nebuly.ai
    resources:
      - elasticquotas/finalizers
    verbs:
      - update
  - apiGroups:
      - nos.nebuly.ai
    resources:
      - elasticquotas/status
    verbs:
      - get
      - patch
      - update
