name: Build Nebulnetes - version "latest"

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  N8S_VERSION: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Set up Helm
        uses: Azure/setup-helm@v3
        with:
          version: v3.10.3

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: make docker-build

      - name: Push Docker images
        run: make docker-push

      - name: Push Helm charts
        run: make helm-push