name: Build GPU Partitioner

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  MIGAGENT_IMG: "ghcr.io/${{ github.repository }}-mig-agent:latest"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: make docker-build-mig-agent

      - name: Push images
        run: make docker-build-mig-agent