name: Build nos

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: make test


  build-operator:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Version
        id: version
        run: head -2 Makefile | cut -d "=" -s -f 2 | xargs

      - name: Build Docker image
        run: make docker-build-operator

      - name: Push Docker image
        run: make docker-push-operator

  build-scheduler:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Version
        id: version
        run: head -2 Makefile | cut -d "=" -s -f 2 | xargs

      - name: Build Docker image
        run: make docker-build-scheduler

      - name: Push Docker image
        run: make docker-push-scheduler

  build-gpu-partitioner:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Version
        id: version
        run: head -2 Makefile | cut -d "=" -s -f 2 | xargs

      - name: Build Docker image
        run: make docker-build-gpu-partitioner

      - name: Push Docker image
        run: make docker-push-gpu-partitioner

  build-gpu-agent:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Version
        id: version
        run: head -2 Makefile | cut -d "=" -s -f 2 | xargs

      - name: Build Docker image
        run: make docker-build-gpu-agent

      - name: Push Docker image
        run: make docker-push-gpu-agent

  build-mig-agent:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Version
        id: version
        run: head -2 Makefile | cut -d "=" -s -f 2 | xargs

      - name: Build Docker image
        run: make docker-build-mig-agent

      - name: Push Docker image
        run: make docker-push-mig-agent

  helm-charts:
    runs-on: ubuntu-22.04
    needs:
      - build-operator
      - build-scheduler
      - build-gpu-partitioner
      - build-gpu-agent
      - build-mig-agent
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Set up Helm
        uses: Azure/setup-helm@v3
        with:
          version: v3.10.3

      - name: Helm login
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} -u $ --password-stdin

      - name: Helm push
        run: make helm-push
