  on:
    workflow_dispatch:
      inputs:
        docker-image:
          description: 'The name of the docker image that will be build'
          required: true
          default: 'mig-handler:latest'
          type: string

  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: "${{ github.repository }}-mig-handler"

  jobs:
    docker:
      runs-on: ubuntu-22.04
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Print pwd
          run: pwd

        - name: Build mig-handler
          run: make docker-build-mig-handler MIG_PARTITIONER_IMG=${{ env.IMAGE_NAME }}

        - name: Push mig-handler
          run: make docker-push-mig-handler MIG_PARTITIONER_IMG=${{ env.IMAGE_NAME }}