name: Docker images - current version

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Version
        id: version
        run: head -2 Makefile | cut -d "=" -s -f 2 | xargs

      - name: Build images
        run: make docker-build

      - name: Push images
        run: make docker-push