name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
    - ".github/**"
    - "README.md"
    - "doc/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - ".github/**"
    - "README.md"
    - "doc/**"

permissions:
  contents: read
  pull-requests: read

jobs:

  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Check license header
        uses: apache/skywalking-eyes@v0.4.0

      - name: Test
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          file: ./cover.out
          flags: unittests
          name: codecov-umbrella


