apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: mig-agent-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
    app.kubernetes.io/component: mig-agent
